mission complete
mate-academy/layout_calendar pull request #1214
Opened 2022-09-14 13:26 UTC by yurii-filiushkin

- [DEMO LINK](https://yurii-filiushkin.github.io/layout_calendar/)
- [TEST REPORT LINK](https://yurii-filiushkin.github.io/layout_calendar/report/html_report/)

2022-09-15 17:27 UTC, marina-tilniak requested changes

2022-09-15 17:27 UTC, marina-tilniak commented on src/index.html
> +      <div class="calendar__day calendar__day--31"></div>
`calendar__day--29` навіщо ці класи?

2022-09-15 18:08 UTC, yurii-filiushkin commented on src/index.html
> +      <div class="calendar__day calendar__day--31"></div>
Я так числа проставив
@for $index from 1 through 31 {
      &--#{$index}::before

2022-09-15 18:23 UTC, yurii-filiushkin commented on src/index.html
> +      <div class="calendar__day calendar__day--31"></div>
Виправив

2022-09-16 18:44 UTC, ivanchuk-yurii approved these changes

2022-09-16 18:44 UTC, ivanchuk-yurii commented on src/styles/blocks/calendar.scss
> +    "sun" #{6 * ($day-width + $gap-value)};
it's better to calculate margins inside `@each` with `list.index`

2024-03-13 06:46 UTC, closed without merging