Calendar task completed
mate-academy/layout_calendar pull request #1286
Opened 2022-10-06 06:26 UTC by Largoxoxo

- [DEMO LINK](https://Largoxoxo.github.io/layout_calendar/)
- [TEST REPORT LINK](https://Largoxoxo.github.io/layout_calendar/report/html_report/)

2022-10-06 06:45 UTC, referee1988 requested changes

2022-10-06 06:45 UTC, referee1988 commented on src/index.html
> +    <div class="calendar calendar--start-day--mon calendar--month-length--31">
```suggestion
    <div class="calendar calendar--start-day_mon calendar--month-length_31">
```

2022-10-06 06:45 UTC, referee1988 commented on src/styles/blocks/calendar.scss
> +        margin-left: $firstDayMargin * $number;
Wrong margin-left
![image](https://user-images.githubusercontent.com/105992827/194231948-c96da2a7-86ab-4461-b73a-03f4f6762d58.png)

2022-10-06 06:45 UTC, referee1988 commented on src/styles/blocks/calendar.scss
> +    transition: all 0.5s ease-out;
At one of the lessons they said it's better not to use ALL
```suggestion
    transition: background-color 0.5s, transform 0.5s;
```

2022-10-06 10:12 UTC, referee1988 approved these changes
Well done!

2022-10-07 13:43 UTC, mykola-koval approved these changes

2022-10-07 13:43 UTC, mykola-koval commented on src/styles/blocks/calendar.scss
> +      :nth-child(n + #{$lastDay + 1}) {
add calendar day selector here

2022-10-07 13:43 UTC, mykola-koval commented on src/styles/blocks/calendar.scss
> +      :first-child {
add calendar day selector here

2022-10-11 08:58 UTC, Largoxoxo commented on src/styles/blocks/calendar.scss
> +      :first-child {
Fixed all issues.

2026-04-05 11:43 UTC, closed without merging