calendar--solution
mate-academy/layout_calendar pull request #1329
Opened 2022-10-18 13:34 UTC by maksym-kostetskyi

https://maksym-kostetskyi.github.io/layout_calendar/
https://maksym-kostetskyi.github.io/layout_calendar/report/html_report/

2022-10-18 17:42 UTC, SanyaBratashchuk requested changes

2022-10-18 17:42 UTC, SanyaBratashchuk commented on src/index.html
> +      <div class="calendar__cell "></div>
```suggestion
      <div class="calendar__cell"></div>
```

2022-10-18 17:42 UTC, SanyaBratashchuk commented on src/styles/calendar.scss
> +  );
move variables to the _variables.scss

2022-10-18 17:42 UTC, SanyaBratashchuk commented on src/styles/calendar.scss
> +    }
You don't need animation for it you just can use translate on hover with transition property

2022-10-20 19:32 UTC, ivanchuk-yurii requested changes

2022-10-20 19:32 UTC, ivanchuk-yurii commented on src/styles/calendar.scss
> +      transition: translate, background-color 0.5s, 0.5s;
```suggestion
      transition: translate 0.5s, background-color 0.5s;
```
is more common

2022-10-20 19:32 UTC, ivanchuk-yurii commented on src/styles/calendar.scss
> +      margin-left: $first-cell-margin * $day-number + $day-number - 101px;
what is the `101px`? I think you should use `$cell-size` here and delete `$first-cell-margin` because you want margin to be the same as cell size

2022-10-22 07:44 UTC, SanyaBratashchuk approved these changes

2024-12-10 18:10 UTC, closed without merging