calendar
mate-academy/layout_calendar pull request #1339
Opened 2022-10-23 20:18 UTC by vlad-boikov

- [DEMO LINK](https://vlad-boikov.github.io/layout_calendar/)
- [TEST REPORT LINK](https://vlad-boikov.github.io/layout_calendar/report/html_report/)

2022-10-25 15:53 UTC, DarkMistyRoom requested changes
Good work, but rename files, you have 2 main.scss and some other comments

2022-10-25 15:53 UTC, DarkMistyRoom commented on src/styles/blocks/calendar.scss
> +  $week-days: "mon" 0, "tue" 1, "wed" 2, "thu" 3, "fri" 4, "sat" 5, "sun" 6;
move it to the _variables

2022-10-25 15:53 UTC, DarkMistyRoom commented on src/styles/utils/_variables.scss
> +$first-day-margin: $cell-side + $gap-size;
be consistent with names. use only camelCase or kebab-case

2022-10-25 15:53 UTC, DarkMistyRoom commented on src/styles/blocks/calendar.scss
> +    transition-duration: 500ms;
list all styles that you apply transition to, it is better for performance

2022-10-26 15:58 UTC, liliia-livandovskaya approved these changes
🔥

2025-02-27 17:30 UTC, closed without merging