calendar was created
mate-academy/layout_calendar pull request #1375
Opened 2022-11-05 12:51 UTC by official-artem

- [DEMO LINK](https://official-artem.github.io/layout_calendar/)
- [TEST REPORT LINK](https://official-artem.github.io/layout_calendar/report/html_report/)

2022-11-05 13:20 UTC, Nazar-Brunarskyi requested changes
and take care of your demo links, cause for now it doesn't work

2022-11-05 13:20 UTC, Nazar-Brunarskyi commented on src/index.html
> +      <div class="calendar__day calendar__day--fri calendar__day--5 calendar__day--hover"></div>
```suggestion
  <body>
    <div class="calendar calendar--start-day--sun calendar--days--27">
      <div class="calendar__day"></div>
      
      <div class="calendar__day"></div>
      
      <div class="calendar__day"></div>
      
      <div class="calendar__day"></div>
      
      <div class="calendar__day"></div>
      
```

2022-11-05 13:20 UTC, Nazar-Brunarskyi commented on src/index.html
> +      <div class="calendar__day calendar__day--fri calendar__day--5 calendar__day--hover"></div>
use nth-child to interact with days

don't add modificator to each day, just for a container

2022-11-05 13:20 UTC, Nazar-Brunarskyi commented on src/styles/blocks/calendar.scss
> +
remove the calendar class from the body and style the body in a different file

2022-11-05 13:20 UTC, Nazar-Brunarskyi commented on src/styles/utils/_extends.scss
> +};
I'm not sure whether you need the extension cause you use it only once

2022-11-05 16:45 UTC, Nazar-Brunarskyi approved these changes
well done)

2022-11-07 11:41 UTC, solaryasha approved these changes

2022-11-07 11:41 UTC, solaryasha commented on src/styles/blocks/calendar.scss
> +  margin: 100px auto 0;
BEM block and margin -> 😈 
Let's move it to the page element

2022-11-07 11:41 UTC, solaryasha commented on src/styles/utils/_extends.scss
> +};
I guess you could change it for the function and then you will get more flexibility

2026-03-01 22:58 UTC, closed without merging