Calendar was created
mate-academy/layout_calendar pull request #1386
Opened 2022-11-07 16:40 UTC by illiashcherbak

- [DEMO LINK](https://illiashcherbak.github.io/layout_calendar/)
- [TEST REPORT LINK](https://illiashcherbak.github.io/layout_calendar/report/html_report/)

2022-11-07 17:54 UTC, KrisPlanka requested changes
calendar should be in the middle of the screen (check readme.md)

2022-11-07 17:54 UTC, KrisPlanka commented on src/index.html
> +      <div class="calendar__cell calendar__cell--first-day--mon"></div>
move modifier to parent element

2022-11-07 17:54 UTC, KrisPlanka commented on src/styles/blocks/calendar.scss
> +      cursor: pointer;
remove cursor pointer from hover, and move to parent

2022-11-07 18:19 UTC, KrisPlanka approved these changes

2022-11-08 08:22 UTC, ivan-kadykalo approved these changes
Well done🚀

2024-03-11 17:04 UTC, closed without merging