completed
mate-academy/layout_calendar pull request #1517
Opened 2022-12-03 08:58 UTC by Vadivel-Babu

- [DEMO LINK](https://Vadivel-Babu.github.io/layout_calendar/)
- [TEST REPORT LINK](https://Vadivel-Babu.github.io/layout_calendar/report/html_report/)

2022-12-04 15:13 UTC, polosanya requested changes
Almost done! Let's try to implement this part of the task:
![image](https://user-images.githubusercontent.com/96409563/205498524-68bd9c5a-dc7f-4495-a002-c335a4a48199.png)
Add modifiers to the calender so you can dynamically change the amount of days and start day by changing the class. E.g, classes `calendar--month-length-30` and `calendar--start-day-fri` will make your calendar look like that:
![image](https://user-images.githubusercontent.com/96409563/205498697-f88b4040-78fd-4784-9e1e-ef4eac4a3966.png)

2022-12-06 14:11 UTC, jstmpelowycz reviewed
nice! but next time – resetting, normalizing should be placed to a dedicated file, BEM-blocks – accordingly

2022-12-06 14:11 UTC, jstmpelowycz commented on src/styles/main.scss
> +$days: "mon" 0, "tues" 1, "wed" 2, "thurs" 3, "fri" 4, "sat" 5, "sun" 6;
```suggestion
$days: 
  "mon" 0, 
  "tue" 1, 
  "wed" 2, 
  "thu" 3, 
  "fri" 4, 
  "sat" 5, 
  "sun" 6;
```

2022-12-06 14:11 UTC, jstmpelowycz approved these changes

2024-12-06 08:26 UTC, closed without merging