done
mate-academy/layout_calendar pull request #1665
Opened 2023-01-11 20:03 UTC by maxonshev

- [DEMO LINK](https://maxonshev.github.io/layout_calendar/)
- [TEST REPORT LINK](https://maxonshev.github.io/layout_calendar/report/html_report/)

2023-01-12 18:22 UTC, polosanya requested changes

2023-01-12 18:22 UTC, polosanya commented on src/index.html
> +    </div>
```suggestion
      <div class="calendar__day"></div>
    </div>
```
Don't leave newlines between parent and child elements

2023-01-12 18:22 UTC, polosanya commented on src/styles/blocks/calendar.scss
> +  width: $calendar-width;
```suggestion
.calendar {
  width: $calendar-width;
```

2023-01-12 18:22 UTC, polosanya commented on src/styles/blocks/calendar.scss
> +    }
![image](https://user-images.githubusercontent.com/96409563/212147542-e6c21791-c291-40f0-b648-307e538fdc66.png)

2023-01-12 18:22 UTC, polosanya commented on src/styles/blocks/calendar.scss
> +  @each $montName, $orderNumber in $startDay {
```suggestion
  @each $dayName, $orderNumber in $startDay {
```
Why it's montName, if it's actually dayName of day of the week?

2023-01-13 18:15 UTC, SanyaBratashchuk approved these changes

2025-03-07 10:52 UTC, closed without merging