Solution
mate-academy/layout_calendar pull request #1702
Opened 2023-01-23 15:16 UTC by Zelinskyi-Serhii

- [DEMO LINK](https://Zelinskyi-Serhii.github.io/layout_calendar/)
- [TEST REPORT LINK](https://Zelinskyi-Serhii.github.io/layout_calendar/report/html_report/)

2023-02-01 16:19 UTC, kirill-vypirovskyi requested changes
GJ, but you should have one more for-loop for regulate month length

2023-02-01 16:19 UTC, kirill-vypirovskyi commented on src/styles/blocks/calendar.scss
> +  "sun" $box-size * 6 + (6 * $gap-between-days);
You can add variables in braces and then multiply sum by 2
```suggestion
  "wed" ($box-size  +  $gap-between-days) * 2,
  "thurs" $box-size * 3 + (3 * $gap-between-days),
  "fri" $box-size * 4 + (4 * $gap-between-days),
  "sat" $box-size * 5 + (5 * $gap-between-days),
  "sun" $box-size * 6 + (6 * $gap-between-days);
```

2023-02-01 16:19 UTC, kirill-vypirovskyi commented on src/styles/blocks/calendar.scss
> +  "sun" $box-size * 6 + (6 * $gap-between-days);
I think it looks better

2023-02-01 16:19 UTC, kirill-vypirovskyi commented on src/index.html
> +      <div class="calendar__day calendar__day--1 calendar__day--tues"></div>
In my opinion it will be better to add modificator to calendar block, not to the first element.

2023-02-01 17:50 UTC, kirill-vypirovskyi approved these changes

2023-02-02 20:47 UTC, illiarerun requested changes

2023-02-02 20:47 UTC, illiarerun commented on src/index.html
> +      <div class="calendar__day calendar__day--31"></div>
remove these modifiers, better use pesudo-classes for selecting needed elements

2023-02-02 20:47 UTC, illiarerun commented on src/styles/blocks/calendar.scss
> +  width: 710px;
use formula to calculate width of container

2023-02-02 20:47 UTC, illiarerun commented on src/styles/blocks/calendar.scss
> +    &--day-#{$day} &__day--1 {
use pseudoclass here
```suggestion
    &--day-#{$day}  {
```

2023-02-02 20:47 UTC, illiarerun commented on src/styles/blocks/calendar.scss
> +    transition: 0.5s;
[checklist](https://github.com/mate-academy/layout_calendar/blob/master/checklist.md) 8th item

2023-02-07 16:42 UTC, sergii-nosachenko requested changes

2023-02-07 16:42 UTC, sergii-nosachenko commented on src/index.html
> +    <div class="calendar calendar--day-fri calendar--day-month-30">
Read the task carefully - you need to rename your modifiers.

Also checklist #2

2023-02-07 16:42 UTC, sergii-nosachenko commented on src/index.html
> +
```suggestion
```

Cleanup your code

2023-02-07 16:42 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
> +    "sun" 6 * ($box-size + $gap-between-days);
Store this in variables.

2023-02-07 16:42 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
> +    "sun" 6 * ($box-size + $gap-between-days);
Read the task carefully on how to name days correctly.

2023-02-07 16:42 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
> +      transform: translate(0, -20px);
```suggestion
      transform: translateY(-20px);
```

2023-02-07 16:42 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
> +    ;
Checklist #12

2023-02-07 16:42 UTC, sergii-nosachenko commented on src/styles/main.scss
>  }
Make body as a separate BEM block with class.

2023-02-07 16:42 UTC, sergii-nosachenko commented on src/styles/utils/_variables.scss
> +$transition-time: 0.3s;
Wrong duration.

2023-02-07 16:42 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
> +      color: yellowgreen;
Add colors to variables.

2023-02-08 11:10 UTC, sergii-nosachenko requested changes

2023-02-08 11:10 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
>        color $transition-time,
There is no color prop to animate.

2023-02-08 11:10 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
>    margin: auto;
Don't set margins to block itself. You could add styles to the parent element to center this block.

2023-02-08 11:10 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
>    @for $num from 28 through 31 {
```suggestion
  @for $num from 28 through $month-length {
```

Maybe, you can add meaningful var for 28 too.

2023-02-08 15:51 UTC, sergii-nosachenko requested changes

2023-02-08 15:51 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
> +  transform: translateY(-50%);
```suggestion
  display: flex;
  flex-wrap: wrap;
  width: $width-calendar;
  gap: $gap-between-days;
```

Overthinked positioning. Just remove these props at all.

2023-02-08 15:51 UTC, sergii-nosachenko commented on src/styles/main.scss
> +@import "blocks/calendar.scss";
You can omit `.scss` in imports.

2023-02-08 16:43 UTC, sergii-nosachenko approved these changes
Good work 👍

2023-07-12 20:11 UTC, closed without merging