created calendar
mate-academy/layout_calendar pull request #1733
Opened 2023-01-31 14:22 UTC by Nordexz

- [DEMO LINK](https://Nordexz.github.io/layout_calendar/)
- [TEST REPORT LINK](https://Nordexz.github.io/layout_calendar/report/html_report/)

2023-02-01 12:17 UTC, YaroslavDzyadiv approved these changes
As for me, it's an awesome work! I found no errors.

2023-02-03 13:57 UTC, Andr1yK requested changes

2023-02-03 13:57 UTC, Andr1yK commented on src/styles/blocks/calendar.scss
> +  margin: 0 auto;
u cant use margins for block (but u can use BEM mix)

2023-02-03 13:57 UTC, Andr1yK commented on src/styles/blocks/calendar.scss
> +    "sun" $cell-with-gap * 6;
move variables to another file

2023-02-07 12:51 UTC, sergii-nosachenko requested changes

2023-02-07 12:51 UTC, sergii-nosachenko commented on src/index.html
> +      <div class="container__calendar calendar calendar--month-length--28 calendar--start-day--wed">
```suggestion
      <div class="calendar calendar--month-length--28 calendar--start-day--wed">
```

Why do you need container modifier?

2023-02-07 12:51 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
> +    @include square(98px);
Better store cell size as a global variable. Why 98 px? Set proper `box-sizing` for all elements.

2023-02-07 12:51 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
> +        height: 100%;
```suggestion
```
Checklist #7

2023-02-07 12:51 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
> +      cursor: pointer;
This prop is for element itself, not for pseudo-class

2023-02-07 12:51 UTC, sergii-nosachenko commented on src/styles/utils/_variables.scss
> +$cell-with-gap: 101px;
Better store gap value separately. And add proper cell width. Sum of these values = cell with gap.

2023-02-07 12:51 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
> +    transition: color 0.5s, transform 0.5s;
You don't change `color` prop on hover, fix it.

2023-02-07 12:51 UTC, sergii-nosachenko commented on src/styles/blocks/calendar.scss
> +    transition: color 0.5s, transform 0.5s;
Maybe 0.5s is also a variable?

2023-02-13 11:17 UTC, illiarerun approved these changes

2025-09-29 20:14 UTC, closed without merging