Calendar
mate-academy/layout_calendar pull request #205
Opened 2021-07-15 10:28 UTC by anton-forzun

2021-07-15 11:19 UTC, mykola-yarchuk requested changes

2021-07-15 11:19 UTC, mykola-yarchuk commented on src/styles/main.scss
> +@for $month-length from 28 to 32 {
```suggestion
@for $month-length from 28 through 31 {
```

2021-07-15 11:19 UTC, mykola-yarchuk commented on src/styles/main.scss
> +  margin-left: 505px;
цей клас перебиває класи calendar--mon calendar--sun і тд. він зайвий зміни логіку так щоб класи для дня з якого починається місяць працювали ок

2021-07-15 11:52 UTC, anton-forzun commented on src/styles/main.scss
> +  margin-left: 505px;
Не можу зрозуміти що потрібно змінити?

2021-07-15 12:40 UTC, anton-forzun commented
- [DEMO LINK](https://anton-forzun.github.io/layout_calendar/)
- [TEST REPORT LINK](https://anton-forzun.github.io/layout_calendar/report/html_report/)

2021-07-16 08:33 UTC, anton-forzun commented
- [DEMO LINK](https://anton-forzun.github.io/layout_calendar/)
- [TEST REPORT LINK](https://anton-forzun.github.io/layout_calendar/report/html_report/)

2021-07-16 08:46 UTC, mykola-yarchuk approved these changes

2021-07-16 08:46 UTC, mykola-yarchuk commented on src/styles/main.scss
> +  transition: transform 0.5s, background-color 0.5s;
https://user-images.githubusercontent.com/35385361/125919783-314ca9b3-ff41-45ff-bffb-c61e98bdef19.mov


https://user-images.githubusercontent.com/35385361/125919901-9ceb693b-4ba1-4b67-8c09-7a82e1277c77.mov

якщо перенести transion в клас day то буде працювати і коли відводиш курсор

2021-07-17 07:32 UTC, closed without merging