add task solution
mate-academy/layout_calendar pull request #2133
Opened 2023-04-27 20:38 UTC by vitvadym

[DEMO LINK](https://vitvadym.github.io/layout_calendar/)

2023-04-28 08:55 UTC, silchyn requested changes

2023-04-28 08:55 UTC, silchyn commented on src/index.html
> +        class="calendar calendar--start-day-wed calendar--month-length-31">
```suggestion
      <div
        class="calendar calendar--start-day--wed calendar--month-length--31"
      >
```

2023-04-28 08:55 UTC, silchyn commented on src/index.html
> +
```suggestion
```

2023-04-28 08:55 UTC, silchyn commented on src/styles/block/container.scss
> +.calendar {
this is not part of `container` block

2023-04-28 08:55 UTC, silchyn commented on src/styles/block/container.scss
> +@import "../utils/_mixins";
shouldn't be there

2023-05-02 16:29 UTC, naziamoff requested changes
please move your blocks to corresponding folders and fix naming

2023-05-02 16:29 UTC, naziamoff commented on src/styles/block/container.scss
> +.calendar {
yeah, does not seem to be a part of container

2023-05-02 16:29 UTC, naziamoff commented on src/styles/utils/_mixins.scss
> +@mixin centered-main-container {
let's think of more descriptive naming. I should understand what is it about by its name. Properties are pretty random. They should be connected by some common thing

2023-05-11 15:18 UTC, silchyn approved these changes

2023-05-11 15:18 UTC, silchyn commented on src/styles/utils/_reset.scss
> +  box-sizing: border-box;
does not look like resetting css

2023-05-11 15:18 UTC, silchyn approved these changes

2024-11-22 21:05 UTC, closed without merging