add solution layout_calendar
mate-academy/layout_calendar pull request #2136
Opened 2023-04-28 08:52 UTC by petrushinsky-kirill

- [DEMO LINK](https://petrushinsky-kirill.github.io/layout_calendar/)
- [TEST REPORT LINK](https://petrushinsky-kirill.github.io/layout_calendar/report/html_report/)

2023-04-28 09:29 UTC, DarkMistyRoom requested changes
Good, but let's add some improvements:

The calendar should always have 7 columns
![image](https://user-images.githubusercontent.com/98764641/235109567-54d92dee-a34e-4b4f-a4d2-3769e97ff95c.png)

2023-04-28 09:29 UTC, DarkMistyRoom commented on src/styles/blocks/calendar__cell.scss
> +}
place the element in the block's file and use nesting

2023-04-28 09:29 UTC, DarkMistyRoom commented on src/styles/blocks/calendar.scss
> +  margin: 0 auto;
Don't add external styles (positioning or margins) to BEM-blocks. Use mix where necessary and move all external styles under element selector.

2023-04-28 09:29 UTC, DarkMistyRoom commented on src/styles/blocks/calendar__cell.scss
> +    cursor: pointer;
move `cursor: pointer;` to the main selector

2023-04-28 09:29 UTC, DarkMistyRoom commented on src/styles/blocks/calendar__cell.scss
> +  transition: 0.5s;
list all transition properties, it is better for performance
https://stackoverflow.com/questions/8947441/css3-transitions-is-transition-all-slower-than-transition-x

2023-05-01 09:02 UTC, OleziO requested changes
Make hover animation a bit faster.

2023-05-01 09:41 UTC, OleziO approved these changes

2025-02-14 14:30 UTC, closed without merging