Finish calendar
mate-academy/layout_calendar pull request #2255
Opened 2023-05-31 11:50 UTC by AntonBaranskyi

[DEMO LINK](https://AntonBaranskyi.github.io/layout_calendar/)

2023-05-31 14:14 UTC, And678 requested changes
Make sure it works in all cases of start-day and month-length, even for invalid ones ([checklist 10](https://github.com/mate-academy/layout_calendar/blob/master/checklist.md)).

On picture: start-day = mon, length = 31:

![image](https://github.com/mate-academy/layout_calendar/assets/23013525/da536b4b-f544-4e38-8b45-450571706b17)

2023-05-31 14:14 UTC, And678 commented on src/index.html
> +      <div class="calendar calendar--month--length-28 calendar--start--day--sat">
[Checklist #2](https://github.com/mate-academy/layout_calendar/blob/master/checklist.md) - [BEM] - Make sure to follow BEM naming convention for complex modifiers: `block-name--modifier-name--modifier-value`;
```suggestion
      <div class="calendar calendar--month-length--28 calendar--start-day--sat">
```

2023-05-31 14:14 UTC, And678 commented on src/index.html
> +      <div class="calendar calendar--month--length-28 calendar--start--day--sat">
In this case
modifier-name = month-length
modifier-value = 28

2023-05-31 14:14 UTC, And678 commented on src/index.html
> +      <div class="calendar calendar--month--length-28 calendar--start--day--sat">
Don't forget to update scss too

2023-06-01 07:40 UTC, tetiana-ivanchenko requested changes
![image](https://github.com/mate-academy/layout_calendar/assets/59209337/3fb12ea4-fa63-4678-bdca-3a7ac8a4eaa9)
please, make sure that after modificators changing all works as expected

2023-06-01 14:42 UTC, closed without merging