layout_calendar
mate-academy/layout_calendar pull request #2359
Opened 2023-06-20 08:12 UTC by iLinuxx

https://ilinuxx.github.io/layout_calendar/

2023-06-20 12:47 UTC, anastasiiavorobiova requested changes
Great start! Let's fix some issues: Modifiers related to the weekdays don't work.

2023-06-21 13:12 UTC, volodymyr-soltys97 requested changes
Good job 👍 
But let's make your code more perfect

2023-06-21 13:12 UTC, volodymyr-soltys97 commented on src/styles/main.scss
> +@import "blocks/calendar";
The import statement should have a relative path: './blocks/calendar';

2023-06-21 13:12 UTC, volodymyr-soltys97 commented on src/styles/blocks/calendar.scss
> +      background-color: green;
Change the background-color from 'green' to 'pink' on hover according to the task description.

2023-06-21 13:12 UTC, volodymyr-soltys97 commented on src/styles/blocks/calendar.scss
> +      margin-left: ($start - 1) * ($day-size+ 1px);
Use $calendar-gap instead of hardcoded '1px' for the margin calculation.

2023-06-21 13:12 UTC, volodymyr-soltys97 commented on src/index.html
> +    >
```suggestion
    <div class="calendar calendar--month-length--30 calendar--start-day--tue">
```

2023-06-21 14:16 UTC, volodymyr-soltys97 approved these changes
Nice work 👍

2024-06-11 13:15 UTC, closed without merging