add task solution
mate-academy/layout_calendar pull request #2372
Opened 2023-06-25 15:24 UTC by Ivanfifan

[DEMO LINK](https://Ivanfifan.github.io/layout_calendar/)
[TEST REPORT LINK](https://Ivanfifan.github.io/layout_calendar/report/html_report/)

2023-06-25 22:03 UTC, nazarmatsevych requested changes
Code looks good but demo link doesn't work, try to rerun "npm run deploy" command or ask for help in fe_chat

2023-06-25 22:03 UTC, nazarmatsevych commented on src/styles/main.scss
> +$start-day: "mon" 0 0, "tue" 1 3, "wed" 2 6, "thu" 3 9, "fri" 4 12, "sat" 5 15, "sun" 6 18;
Create a separate file for variables

2023-06-26 10:37 UTC, Anastasiia-Svintsova requested changes
Hey! Seems the project is not deployed. Ask questions in the chat if you need a hint 
![image](https://github.com/mate-academy/layout_calendar/assets/99403198/4f905d97-3580-481b-8a72-99059fc77218)

2023-06-26 10:37 UTC, Anastasiia-Svintsova commented on src/styles/main.scss
> +  width: $cell-size * 7+20;
Don't use mystery numbers. Move 7 and 20 to variables

2023-06-26 10:37 UTC, Anastasiia-Svintsova commented on src/styles/variables.scss
> +$start-day: "mon" 0 0, "tue" 1 3, "wed" 2 6, "thu" 3 9, "fri" 4 12, "sat" 5 15, "sun" 6 18;
For what purposes do we need to use the second number for each item? You can simplify it and calculate the necessary values 
```suggestion
$start-day: "mon" 1,  "tue" 2,  "wed" 3,  "thu" 4,  "fri" 5,  "sat" 6,  "sun" 7;
```

2023-06-26 15:57 UTC, mykhalenych requested changes
your demo link isn't working

2023-06-26 16:06 UTC, anastasiiavorobiova requested changes
Good code! Unfortunately, your demo link doesn't work: https://mate-academy.github.io/layout_task-guideline/#important use this instruction (18) to deploy your site

2023-06-26 16:24 UTC, closed without merging