solution
mate-academy/layout_calendar pull request #240
Opened 2021-08-22 18:25 UTC by sgw8

- [DEMO LINK](https://sgw8.github.io/layout_calendar/)

2021-08-25 08:16 UTC, CouldSweeT requested changes

2021-08-25 08:16 UTC, CouldSweeT commented on src/styles/_vars.scss
> +$days:
Хорошая работа, одна ошибочка
```suggestion
$dayBackground: #eee;
$sizeCalendar: ($daySize * 7) + ($gap * 7);
$days:
```
И вроде как все

2021-08-25 14:11 UTC, OleksiiBlezniuk approved these changes
Good job! 🚀

2021-08-31 09:23 UTC, OleksiiBlezniuk approved these changes

2024-05-06 12:49 UTC, closed without merging