add task solution
mate-academy/layout_calendar pull request #2455
Opened 2023-07-13 14:22 UTC by Liubomyr19

[DEMO LINK](https://Liubomyr19.github.io/layout_calendar/)
[TEST REPORT LINK](https://Liubomyr19.github.io/layout_calendar/report/html_report/)

2023-07-13 17:50 UTC, loralevitska requested changes
Good job! There are things that should be fixed:

- fix month-length modifier 
![image](https://github.com/mate-academy/layout_calendar/assets/70009205/80fc816e-98ca-4c16-86b0-26b1bb521943)

2023-07-13 17:50 UTC, loralevitska commented on src/styles/main.scss
> +    background-color: #eee;
It is a good practice to make all colors variable

2023-07-13 17:50 UTC, loralevitska commented on src/styles/main.scss
> +    transform: all 0.5s;
```suggestion
    transition: transform 0.5s;
```

2023-07-13 17:50 UTC, loralevitska commented on src/styles/main.scss
> +  $start-day: "mon" 0,"tue" 1,"wed" 2,"thu" 3,"fri" 4,"sat" 5,"sun" 6;
Move variables to separate file

2023-07-14 08:00 UTC, DarkMistyRoom requested changes
- A calendar should always have 7 columns

<img width="483" alt="image" src="https://github.com/mate-academy/layout_calendar/assets/98764641/d5a9f029-dad9-4845-a15b-348cfb2bd195">

- fix the modifiers. length doesn't work. start day applies wrong indent
<img width="1517" alt="image" src="https://github.com/mate-academy/layout_calendar/assets/98764641/d96396d7-7978-4392-b7fc-817326d947f3">

- also check the syntax. it should be like `calendar--start-day--28`

- no need to compile these files to src
<img width="303" alt="image" src="https://github.com/mate-academy/layout_calendar/assets/98764641/415b46c8-a2b3-4596-adb6-633cdf091e23">

2023-07-14 08:00 UTC, DarkMistyRoom commented on src/styles/main.scss
> +$field--hover-color: pink;
move them to the `variables` file

2023-07-14 08:00 UTC, DarkMistyRoom commented on src/styles/main.scss
> +  margin: 9px;
Don't add external styles (positioning or margins) to BEM-blocks. Use mix where necessary and move all external styles under element selector.

2023-07-15 12:12 UTC, VitaliyBodnar requested changes
- month-length modifier still not working
![Screenshot 2023-07-15 at 15 10 51](https://github.com/mate-academy/layout_calendar/assets/64746943/8a13f4e7-4005-4593-9c9b-d3263d4f8d71)

2023-07-15 12:12 UTC, VitaliyBodnar commented on src/styles/main.scss
> +$field--hover-color: pink;
not fixed

2023-07-15 12:12 UTC, VitaliyBodnar commented on src/styles/main.scss
> +  margin: 9px;
not fixed

2023-07-17 17:24 UTC, SanyaBratashchuk requested changes
Remove extra cell 
![image](https://github.com/mate-academy/layout_calendar/assets/97547824/d0b47bb3-843a-4de4-8e28-8a6c9cfba910)

2023-07-18 16:20 UTC, loralevitska requested changes
Hi, I see you haven't fixed previous comments, maybe you did not push your changes? If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review

2023-07-18 16:20 UTC, loralevitska commented on src/styles/main.scss
> +$field--hover-color: pink;
According previous comment you should move this variables to your file `_variables.scss` 
![image](https://github.com/mate-academy/layout_calendar/assets/70009205/a1e9c117-7bd3-481d-b40e-24dd4552b11d)

2023-07-18 16:20 UTC, loralevitska commented on src/styles/main.scss
> +  margin: 9px;
Improve it 
![image](https://github.com/mate-academy/layout_calendar/assets/70009205/e3f9381d-a44b-4c9a-98f9-2d0aad08a5ef)
```suggestion
```

Use margins for mix class or for body tag in your situation

2023-07-19 07:35 UTC, closed without merging