Calendar done
mate-academy/layout_calendar pull request #248
Opened 2021-08-25 09:46 UTC by Sasha-Krasnoshchokov

[DEMO LINK](https://Sasha-Krasnoshchokov.github.io/layout_calendar/)

2021-08-25 16:21 UTC, Bohdan-Kochetov approved these changes
Все класно!
Good luck!

2021-08-25 16:21 UTC, Bohdan-Kochetov commented on src/styles/main.scss
> +$month-length: 28;
на мою думку дуже важка формула дня визначення ширини простору для клітинок календаря.
можна просто змінну помножити на 7 і додати 7(gap) . а падінги не вказувати а вілцентрувати justify-content-center.

2021-08-26 08:02 UTC, aliceblunt8 requested changes

2021-08-26 08:02 UTC, aliceblunt8 commented on src/index.html
> +      <div class="month">
read the task carefully, you should have add classes to the calendar itself
https://github.com/mate-academy/layout_calendar

1. Implement start-day modifier for the calendar with mon, tue, wed, thu, fri, sat and sun values
2. Add a modifier month-length for the calendar with values 28, 29, 30 and 31

2021-08-30 09:43 UTC, herkoss approved these changes
Great!👍😊

2022-07-08 12:40 UTC, closed without merging