layout_calendar PR
mate-academy/layout_calendar pull request #253
Opened 2021-08-25 16:06 UTC by Rocketjet

- [DEMO LINK](https://Rocketjet.github.io/layout_calendar/)

2021-08-26 10:23 UTC, zhenia-verbitskaya reviewed
Хорошая работа! Прикольно придумал с названиями дней ))

2021-08-26 10:23 UTC, zhenia-verbitskaya commented on src/styles/blocks/page.scss
> +  }
```suggestion
    width: #{$cell-size * 7 + 10px};    
  }
```
Лишняя пустая строка. Есть еще парочка таких по файлам. 
Не совсем поняла, что за 10рх в ширине календаря. Возможно, если это значение может меняться, его стоит тоже задать переменной.

2021-08-26 10:23 UTC, zhenia-verbitskaya commented on src/styles/blocks/calendar.scss
> +    transition: 500ms;
transition: 500ms и transition-duration: 500ms это одно и то же и, насколько я знаю, записывается на сам элемент, а не на hover

2021-08-26 11:36 UTC, OleksiiBlezniuk requested changes
Нужно исправить пару комментов🙂

2021-08-26 11:36 UTC, OleksiiBlezniuk commented on src/index.html
> +    </div>
🔥

2021-08-26 11:36 UTC, OleksiiBlezniuk commented on src/styles/blocks/calendar.scss
> +  }
Не забывай указывать свойства, которые ты анимируешь в transition

2021-08-26 11:36 UTC, OleksiiBlezniuk commented on src/styles/blocks/calendar.scss
> +  }
```suggestion
  &__cell:hover {
    background: pink;
    transform: translateY(-20px);
  }

  @each $day, $day-number in $start-day {
    &--start-day_#{$day} &__cell:first-child {
      margin-left: ($day-number *($cell-size + $cell-gap));
    }
  }
```

2021-08-26 11:36 UTC, OleksiiBlezniuk commented on src/styles/blocks/calendar.scss
> +}
```suggestion
    }
  }
}
```

2021-08-26 11:36 UTC, OleksiiBlezniuk commented on src/styles/blocks/page.scss
> +  }
```suggestion
    width: #{$cell-size * 7 + 10px};
  }
```

2021-08-26 11:36 UTC, OleksiiBlezniuk commented on src/styles/utilities/_extends.scss
> +}
У тебя этот extend применяется только один раз, не думаю что обязательно нужно было выносить эти правила в него

2021-08-26 11:36 UTC, OleksiiBlezniuk commented on src/styles/blocks/page.scss
> +  }
10px - слишком много, если это означает расстояние между ячейками - то там будет меньше🙂

<img width="1440" alt="Снимок экрана 2021-08-26 в 14 29 53" src="https://user-images.githubusercontent.com/84275496/130955230-8165f2fb-4b2c-4622-a86b-9e95c4dd1378.png">

2021-08-26 11:43 UTC, bitsbymax commented on src/styles/utilities/_extends.scss
> +}
застосовується двічі, та і кількість коду сильно меньша)

2021-08-26 11:49 UTC, bitsbymax commented on src/styles/blocks/page.scss
> +  }
"- Use flex with `1px` gap and limit its width to exactly 7 columns + `10px` paddings" - з вимог до завдання. Тому і вказав 10px. Вони входять в загальну ширину - 710px. Але по факту там і 6px достатньо.

2021-08-27 07:32 UTC, OleksiiBlezniuk approved these changes

2021-08-27 07:32 UTC, OleksiiBlezniuk commented on src/index.html
> +      <div class="calendar__cell calendar__cell--date_1"></div>
```suggestion
      <div class="calendar__cell calendar__cell--date-1"></div>
```

2021-08-31 09:29 UTC, OleksiiBlezniuk approved these changes

2024-05-29 15:34 UTC, closed without merging