add task solution
mate-academy/layout_calendar pull request #2565
Opened 2023-07-31 17:17 UTC by MishaLehotskyi

- [DEMO LINK](https://MishaLehotskyi.github.io/layout_calendar/)
- [TEST REPORT LINK](https://MishaLehotskyi.github.io/layout_calendar/report/html_report/)

2023-07-31 20:03 UTC, Andriy-Shymkiv requested changes

2023-07-31 20:03 UTC, andriy-shymkiv commented on src/index.html
> +
you don't need this empty lines here between

2023-07-31 20:03 UTC, Andriy-Shymkiv commented on src/styles/blocks/calendar.scss
> +  }
this loop didn't work, because I still see 28,29,30,31 day in your demo

2023-07-31 20:03 UTC, Andriy-Shymkiv commented on src/styles/main.scss
> +  width: 100vw;
body width is 100% by default, no need to set it here

2023-08-01 14:41 UTC, mykhalenych approved these changes

2024-06-26 19:34 UTC, closed without merging