first start
mate-academy/layout_calendar pull request #2584
Opened 2023-08-09 20:30 UTC by olhry

[DEMO LINK]
https://olhry.github.io/layout_calendar/

2023-08-10 07:00 UTC, maxim2310 requested changes
Good work, just check out your calendar length

2023-08-10 07:00 UTC, maxim2310 commented on src/styles/main.scss
> +  }
this part is not working, you can check it if you change class in calendar

2023-08-10 13:41 UTC, olhry commented on src/styles/main.scss
> +  }
Я не розумію як це виправити. Допоможіть будь ласка.

2023-08-10 16:58 UTC, maxim2310 commented on src/styles/main.scss
> +  }
краще писати у чатик для цього, там тобі швидше допоможуть

2023-08-10 17:15 UTC, maxim2310 commented on src/styles/main.scss
> +  }
![image](https://github.com/mate-academy/layout_calendar/assets/96265844/fbdba356-21be-4753-9cac-e0e5723f8eae)
у тебе помитка тут і в верстці було неспівпадіння

2023-08-10 18:56 UTC, olhry commented on src/styles/main.scss
> +  }
Максим, дуже дякую, все запрацювало

2023-08-10 19:10 UTC, olhry commented
Все працює, але я не бачу значок на оновлення запросу до ментора.

2023-08-12 06:41 UTC, sTorba24 approved these changes
Good work!

2024-04-05 21:33 UTC, closed without merging