add calendar task
mate-academy/layout_calendar pull request #2663
Opened 2023-09-05 11:57 UTC by AnoriFrell

[DEMO LINK](https://AnoriFrell.github.io/layout_calendar/)
[TEST REPORT LINK](https://AnoriFrell.github.io/layout_calendar/report/html_report/)

2023-09-05 12:15 UTC, anastasiiavorobiova requested changes
Awesome work! 
<img width="1136" alt="Screenshot 2023-09-05 at 15 14 04" src="https://github.com/mate-academy/layout_calendar/assets/135232001/4d1c57a2-d0c5-474c-9c6c-211f4ae00d0d">
Might I suggest that you fix your last day to meet the modifier?

2023-09-06 08:00 UTC, etojeDenys requested changes
should be 31 cells 
<img width="468" alt="image" src="https://github.com/mate-academy/layout_calendar/assets/70220667/23cf72ea-a2ef-4e93-a2af-16e38f4602bb">
<img width="196" alt="image" src="https://github.com/mate-academy/layout_calendar/assets/70220667/b1d9d112-0cb4-4807-9f5b-5348201a5c13">

2023-09-06 08:33 UTC, OleziO requested changes
Fix day logic. If you have any questions - feel free to ask them in `fe_chat`
![image](https://github.com/mate-academy/layout_calendar/assets/56752562/49cd6805-ae31-4385-97cd-3319348d03c1)

2023-09-06 08:33 UTC, OleziO commented on src/styles/main.scss
> +  box-sizing: border-box;
The better practice is to set this property to only the * selector. Remove it from all other places to avoid code duplication.

2023-09-06 09:46 UTC, VitaliyBondarenko1982 approved these changes
Well done

2025-01-09 17:23 UTC, closed without merging