add task solution
mate-academy/layout_calendar pull request #2833
Opened 2023-10-20 14:19 UTC by KaterynaEV

- [DEMO LINK](https://KaterynaEV.github.io/layout_calendar/)
- [TEST REPORT LINK](https://KaterynaEV.github.io/layout_calendar/report/html_report/)

2023-10-20 15:31 UTC, volodymyr-soltys97 requested changes
Good job  👍 
1. The modifier for start day working incorrectly
<img width="1512" alt="image" src="https://github.com/mate-academy/layout_calendar/assets/64750958/3a0a6ddb-d368-4c99-9d1a-0e3d11a37295">

2. Need to implement the modifier for month length

3. This part or the task is incomplete
<img width="687" alt="image" src="https://github.com/mate-academy/layout_calendar/assets/64750958/92359368-187a-4c7d-8654-52df71737c19">

2023-10-21 06:37 UTC, sTorba24 requested changes
Almost good! 
still not resolved issue with start day modifier
Maybe you forgot to run deploy?

![image](https://github.com/mate-academy/layout_calendar/assets/55200530/c21ba8f8-d97b-4aa3-9d42-f6455edbdcbc)

2023-10-21 06:37 UTC, sTorba24 commented on src/index.html
> +      <div class="calendar__day calendar__day--start-day_mon"></div>
```suggestion
      <div class="calendar__day"></div>
```

2023-10-21 06:37 UTC, sTorba24 commented on src/index.html
> +    <div class="calendar">
```suggestion
    <div class="calendar calendar--start-day-mon calendar--month-length-31">
```

2023-10-21 06:37 UTC, sTorba24 commented on src/index.html
> +    <div class="calendar">
add modifiers to calendar block

2023-10-21 12:54 UTC, Andriy-Shymkiv requested changes

2023-10-21 12:54 UTC, Andriy-Shymkiv commented on src/styles/main.scss
> +  flex-direction: row;
it is a default value for flexbox

2023-10-21 12:54 UTC, Andriy-Shymkiv commented on src/styles/main.scss
> +}
move it to the end of the file

2023-10-21 12:54 UTC, Andriy-Shymkiv commented on src/styles/main.scss
> +    justify-content: center;
do you really need this?
```suggestion
```

2023-10-22 06:32 UTC, OleziO requested changes
Fix week-day and month-length selectors
![image](https://github.com/mate-academy/layout_calendar/assets/56752562/4ba0ccd5-82d7-45a8-90bb-4984dfc61119)

2023-10-22 06:32 UTC, OleziO commented on src/styles/main.scss
> +    box-sizing: border-box;
Move to the * selector and remove it from all other places.

2023-10-22 06:32 UTC, OleziO commented on src/styles/main.scss
> +    font-family: Arial, Helvetica, sans-serif;
Move to the html selector and remove it from all other places.

2023-10-22 08:34 UTC, etojeDenys approved these changes
good job

2023-11-04 16:32 UTC, closed without merging