calendar done
mate-academy/layout_calendar pull request #2973
Opened 2023-12-11 19:37 UTC by DenisFrankovskyi

https://denisfrankovskyi.github.io/layout_calendar/
denisfrankovskyi.github.io/layout_calendar/report/html_report/

2023-12-11 19:59 UTC, l4st1m0za requested changes
Good job, but some changes needed!

2023-12-11 19:59 UTC, l4st1m0za commented on src/styles/variables.scss
> +$month-lenth: ("28", "29", "30", "31");
The values in the 'month-length' list are strings, but they should be integers. Update to [28, 29, 30, 31].

2023-12-11 19:59 UTC, l4st1m0za commented on src/styles/calendar.scss
> +  max-width: calc($calendar-day-width * 8);
The max-width is not correct, it should be 7 columns * (width + gap) + padding.

2023-12-11 19:59 UTC, l4st1m0za commented on src/styles/calendar.scss
> +}
The body styling should not be in the calendar.scss file as it is a global style. It should be moved to a different file such as global.scss.

2023-12-11 19:59 UTC, l4st1m0za commented on src/styles/calendar.scss
> +    &:hover {
The cursor should change to a pointer on hover. Add 'cursor: pointer;' to .calendar__day:hover.

2023-12-11 19:59 UTC, l4st1m0za commented on src/styles/calendar.scss
> +    border: 1px solid black;
The border should be included in the box-sizing of the elements. Add 'box-sizing: border-box;' to .calendar__day.

2023-12-11 19:59 UTC, l4st1m0za commented on src/styles/calendar.scss
> +    margin-left: ($calendar-day-width + (3 * $day-gap)) * $n;
The calculation of the margin-left is not correct, it should be multiplied by ($n - 1) to account for the first day of the week starting from 0.

2023-12-12 07:29 UTC, maxim2310 approved these changes
Well done!!!

2025-09-22 12:57 UTC, closed without merging