create-calendar
mate-academy/layout_calendar pull request #3023
Opened 2024-01-04 10:51 UTC by Prokopovych16

- [DEMO LINK](https://Prokopovych16.github.io/layout_calendar/)

2024-01-04 13:20 UTC, OleziO requested changes
![image](https://github.com/mate-academy/layout_calendar/assets/56752562/e260cbb4-2d2a-4f3b-819c-4b2242500e5a)
Align the calendar to the center of the screen (Not to the top)
![image](https://github.com/mate-academy/layout_calendar/assets/56752562/917b070f-61b2-4bde-b085-249b96305cf3)
Fix the weekday selector.
![image](https://github.com/mate-academy/layout_calendar/assets/56752562/86546689-1750-4326-a839-46ac07c47b69)
Fix day count selector

2024-01-08 09:08 UTC, etojeDenys requested changes
you forgot to add "px" here
<img width="234" alt="image" src="https://github.com/mate-academy/layout_calendar/assets/70220667/034819a3-2022-4d25-9cfc-609f5628354a">


this how your  app must work: [link](https://www.loom.com/share/3dcf1ba5147f45139ef2d1a0d340b0d3?sid=905026f1-aba6-4842-9578-9138943410f9)

2024-01-08 18:55 UTC, anastasiia-tilikina requested changes
GJ!

Let's just fix some tiny issue here)

2024-01-08 18:55 UTC, anastasiia-tilikina commented on src/styles/main.scss
> +      opacity: 0;
it is better to use display: none here. I still can hover over hidden days and have cursor pointer

2024-01-08 19:14 UTC, l4st1m0za approved these changes
GJ!

2024-11-20 19:35 UTC, closed without merging