Develop
mate-academy/layout_calendar pull request #3096
Opened 2024-01-23 15:38 UTC by vovan4ik1

- [DEMO LINK](https://vovan4ik1.github.io/layout_calendar/)

2024-01-23 15:54 UTC, Viktor-Kost requested changes
please check your deploy since demo link leads to 404 page

2024-01-23 15:54 UTC, Viktor-Kost commented on src/index.html
> +
```suggestion
```

2024-01-23 15:54 UTC, Viktor-Kost commented on src/index.html
> +    <div class="calendar calendar--start-day-wed calendar--mouth-lenght-29">
```suggestion
    <div class="calendar calendar--start-day--wed calendar--mouth-lenght--29">
```

2024-01-23 15:54 UTC, Viktor-Kost commented on src/styles/calendar.scss
> +    &--start-day-#{$day} &__day:first-child {
```suggestion
    &--start-day--#{$day} &__day:first-child {
```

2024-01-23 15:54 UTC, Viktor-Kost commented on src/styles/calendar.scss
> +    &--mouth-length-#{$days-number} &__day:nth-child(n + #{$days-number + 1}) {
```suggestion
    &--mouth-length--#{$days-number} &__day:nth-child(n + #{$days-number + 1}) {
```

2024-01-23 15:54 UTC, Viktor-Kost commented on src/styles/calendar.scss
> +    transition: 500ms;
add transition properties

2024-01-23 15:54 UTC, Viktor-Kost commented on src/styles/calendar.scss
> +    box-sizing: border-box;
move to `*` selector

2024-01-23 16:18 UTC, Viktor-Kost requested changes
I see you've not added any changes yet
<img width="718" alt="Screenshot 2024-01-23 at 18 18 17" src="https://github.com/mate-academy/layout_calendar/assets/117587463/42a764b7-70fe-4b46-84e3-0f10a3781002">

2024-01-26 16:09 UTC, witflash requested changes
Привіт!
Після ревʼю Віктора в репозиторії на GitHub від тебе змін ніяких немає, можливо, ти не закомітив або не запушив їх. Перевір, будь ласка, цей момент. Бо можливо, ти все підправив, але просто не пушнув в репо.

Зараз в тебе залишається два основних моменти:
1. Немає оновлення в readme файлі (там, де ти мав прописати посилання на своє DEMO).
2. Загалом, твоя DEMO https://vovan4ik1.github.io/layout_calendar/ лінка не працює, оскільки, можливо, не виконаний `npm run deploy` команда. 

Якщо під час виконання деплою в тебе виникла якась помилка, то напиши в чат, потрібно буде розібратись з цією траблою. Та й загалом, якщо щось не зрозуміло по цьому завданню, або по ревʼю, то теж пиши в чат, щоб з усім розібратись і не залишалось незрозумілих для тебе моментів.

2024-01-26 16:40 UTC, closed without merging