add task solution
mate-academy/layout_calendar pull request #3097
Opened 2024-01-23 20:39 UTC by Andrew77788

- [DEMO LINK](https://Andrew77788.github.io/layout_calendar/)
- [TEST REPORT LINK](https://Andrew77788.github.io/layout_calendar/report/html_report/)

2024-01-24 07:09 UTC, etojeDenys requested changes

2024-01-24 07:09 UTC, etojeDenys commented on src/styles/main.scss
> +    &_start-day-#{$start-day}
```suggestion
    &-start-day-#{$start-day}
```

2024-01-24 07:09 UTC, etojeDenys commented on src/styles/main.scss
> +    &_length-#{$last-day}
```suggestion
    &-length-#{$last-day}
```

2024-01-24 07:09 UTC, etojeDenys commented on src/index.html
> +  <body class="calendar calendar---start-day-mon calendar---length-31">
```suggestion
  <body class="calendar calendar-start-day-mon calendar-length-31">
```

2024-01-24 07:09 UTC, etojeDenys commented on src/styles/main.scss
> +);
move vars to separate file

2024-01-24 19:03 UTC, Viktor-Kost requested changes
Great job!
Some minor fixes needed

2024-01-24 19:03 UTC, Viktor-Kost commented on src/index.html
> +  <body class="calendar calendar---start-day-mon calendar---length-31">
either use as mentor showed or do like this (to follow BEM recommendations)
```suggestion
  <body class="calendar calendar--start-day--mon calendar--month-length--31">
```

2024-01-24 19:03 UTC, Viktor-Kost commented on src/styles/calendar.scss
> +  width: 706;
this value shouldn't be hardcoded. use calculation based on cell width and gap between them

2024-01-24 19:03 UTC, Viktor-Kost commented on src/styles/calendar.scss
> +  font-family: Arial, Helvetica, sans-serif;
move to `html` tag

2024-01-24 19:03 UTC, Viktor-Kost commented on src/styles/calendar.scss
> +    box-sizing: border-box;
move to `*` selector

2024-01-24 19:03 UTC, Viktor-Kost commented on src/styles/calendar.scss
> +      transition-duration: $animation-duration;
move to `&__day` and add `transition-property` as well

2024-01-24 19:03 UTC, Viktor-Kost commented on src/styles/calendar.scss
> +    &---start-day-#{$start-day}
```suggestion
    &--start-day--#{$start-day}
```

2024-01-24 19:03 UTC, Viktor-Kost commented on src/styles/calendar.scss
> +    &---length-#{$last-day}
```suggestion
    &--length--#{$last-day}
```

2024-01-24 19:30 UTC, Andrew77788 commented on src/styles/calendar.scss
> +    box-sizing: border-box;
Не розумію, ось цей момент, якщо я зроблю так 
*{   background-color: $background-color;
border: 1px solid $border-color;
box-sizing: border-box;
}
це ж не буде правильно, що ви мали на увазі ?)

2024-01-25 08:28 UTC, OleziO approved these changes

2024-08-13 13:57 UTC, closed without merging