add solution
mate-academy/layout_calendar pull request #3375
Opened 2024-04-15 18:53 UTC by happytravels38

I was on a call with mentor about this task but still can not figure out why I can not pass all tests. 
Please help me with this.

- [DEMO LINK](https://happytravels38.github.io/layout_calendar/)
- [TEST REPORT LINK](https://happytravels38.github.io/layout_calendar/report/html_report/)

❗️ Copy this `Checklist` to the `Pull Request` description after links, and put `- [x]` before each point after you checked it.

- [ x ] Changing 'month-lengh' and 'start-day' modifier in the code element
reflects in changing calendar layout
- [ x ] Each day has no modifiers, only class (eg. calendar__day)
- [ x ] All `Typical Mistakes` from `BEM` lesson theory are checked.
- [ x ] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2024-04-16 05:21 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-04-16 05:21 UTC, volodymyr-soltys97 commented on src/styles/index.scss
> +$days: ('mon' 0, 'tue' 1, 'wed' 2, 'thu' 3, 'fri' 4, 'sat' 5, 'sun' 6);
Move variables to the separate file

2024-04-16 05:21 UTC, volodymyr-soltys97 commented on src/styles/index.scss
> +    }
```suggestion
    &:hover {
       transform: translateY(-20px);
       background-color: #ffbfcb;
       transition: 0.5s;
    }
```

2024-04-17 15:57 UTC, happytravels38 commented
I did suggested changes but still can not passed the tests

2024-04-17 17:16 UTC, TarasHoliuk commented
For mentors: do not reject because of failed tests - didn't find the reason for it on the Q&A

2024-04-17 17:17 UTC, andriy-shymkiv approved these changes

2025-06-16 18:32 UTC, closed without merging