Develop
mate-academy/layout_calendar pull request #3599
Opened 2024-07-14 17:45 UTC by RomanMartseniuk

- [DEMO LINK](https://RomanMartseniuk.github.io/layout_calendar/)
- [TEST REPORT LINK](https://RomanMartseniuk.github.io/layout_calendar/report/html_report/)

- [X] Changing 'month-lengh' and 'start-day' modifier in the code element
reflects in changing calendar layout
- [X] Each day has no modifiers, only class (eg. calendar__day)
- [X] All `Typical Mistakes` from `BEM` lesson theory are checked.
- [X] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2024-07-14 19:54 UTC, vadiimvooo requested changes
Good job, but you have to use scss files for styling your components. Feel free to ask for help in fe_chat.

2024-07-14 19:54 UTC, vadiimvooo commented on src/css/style.css
You have to use scss file instead of default css. Please fix it.

2024-07-15 07:05 UTC, RomanMartseniuk commented
Scss was used in this project ./src/scss/...

2024-07-15 07:15 UTC, lerastarynets approved these changes
lgtm 🚀

2025-12-26 21:04 UTC, closed without merging