add task solution
mate-academy/layout_calendar pull request #3640
Opened 2024-08-06 20:19 UTC by WhyCame

- [DEMO LINK](https://WhyCame.github.io/layout_calendar/)
- [TEST REPORT LINK](https://WhyCame.github.io/layout_calendar/report/html_report/)

2024-08-07 05:54 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-08-07 05:54 UTC, volodymyr-soltys97 commented on src/styles/main.scss
> +$calendar-width: $calendar-box * 7 + $gap * 6 + $padding * 2;
Move variables to the separate file

2024-08-07 05:54 UTC, volodymyr-soltys97 commented on src/styles/main.scss
> +  );
The same here

2024-08-07 05:54 UTC, volodymyr-soltys97 commented on src/styles/main.scss
> +    ),
The formula must be calculated inside the loop
```suggestion
    'tue': 1,
    'wed': 2,
    'thu': 3,
    'fri': 4,
    'sat': 5,
    'sun': 6,
```

2024-08-18 18:28 UTC, vadiimvooo approved these changes
LGTM

2026-06-03 12:41 UTC, closed without merging