calendar layout solution
mate-academy/layout_calendar pull request #405
Opened 2021-11-23 18:24 UTC by levix2l

- [DEMO LINK](https://levix2l.github.io/layout_calendar/)

2021-11-24 09:56 UTC, Oleksandr-Leshchenko requested changes

2021-11-24 09:56 UTC, Oleksandr-Leshchenko commented on src/index.html
> +  <body class="container">
http://joxi.ru/xAePKXyHbOj5e2

2021-11-24 09:56 UTC, Oleksandr-Leshchenko commented on src/styles/utils/_variables.scss
> +  "sun" 0;
Стартовый день работает не правильно. Сам подумай, по твоей формуле выходит, что понедельник получает 6-кратный сдвиг вправо, когда должен стоять в начале

2021-11-24 10:00 UTC, levix2l commented on src/styles/utils/_variables.scss
> +  "sun" 0;
да, я похоже не так понял задание

2021-11-24 10:55 UTC, Oleksandr-Leshchenko approved these changes

2021-11-25 09:29 UTC, ArtemTopolskyi approved these changes

2026-06-20 23:00 UTC, closed without merging