solution to calendar
mate-academy/layout_calendar pull request #415
Opened 2021-11-24 11:59 UTC by mykola-koval

- [DEMO LINK](https://mykola-koval.github.io/layout_calendar/)
- [TEST REPORT LINK](https://mykola-koval.github.io/layout_calendar/report/html_report/)

2021-11-24 14:38 UTC, Oleksandr-Leshchenko approved these changes

2021-11-24 14:38 UTC, Oleksandr-Leshchenko commented on src/styles/calendar.scss
> +  }
num можно было определить от 0 до 6, тогда не пришлось бы отнимать единицу в конце

2021-11-24 14:38 UTC, Oleksandr-Leshchenko commented on src/styles/calendar.scss
> +    }
При подстановке 31 у тебя исчезает 32 день. Оно то работает, но выглядит не очень умно. Я бы сделал через nth-last-child()

2021-11-25 09:26 UTC, ArtemTopolskyi requested changes

2021-11-25 09:26 UTC, ArtemTopolskyi commented on src/index.html
> +      <div class="calendar__day calendar__day--31"></div>
Действительно ли все эти модификаторы необходимы? В задании необходимо проставить номера используя css

2021-11-26 09:29 UTC, ArtemTopolskyi approved these changes

2022-12-19 11:06 UTC, closed without merging