calendar was created
mate-academy/layout_calendar pull request #483
Opened 2021-12-31 11:30 UTC by maksym-mishchanchuk

2021-12-31 12:21 UTC, jursylian reviewed
Отличная работа!!!! Нужно немножко доработать и все будет супер!

2021-12-31 12:21 UTC, jursylian commented on src/index.html
> +        <div class="calendar__day day1"></div>
в `html` не должно быть чисел, их нужно добавлять в `scss` при помощи псевдоэлемента  `before`  и цикла `@for`

2021-12-31 12:21 UTC, jursylian commented on src/styles/blocks/calendar.scss
> +  background-color: $bg-block-day;
тут лучше добавить пустую строку)

2021-12-31 12:21 UTC, jursylian commented on src/styles/blocks/calendar.scss
> +  align-items: center;
```suggestion
  align-items: center;
  justify-content: center;
```
можно сделать `placeholder` и добавить в файл `_extend`

2021-12-31 12:21 UTC, jursylian commented on src/styles/blocks/calendar.scss
> +  justify-content: center;
и это тоже, у них у всех одна функция выравнивание, также можно посмотреть, где эти свойства еще повторяются, чтобы не дублировать код)

2021-12-31 12:21 UTC, jursylian commented on src/styles/blocks/main-container.scss
> +  justify-content: center;
например, здесь

2021-12-31 12:21 UTC, jursylian commented on src/styles/index.scss
> +@import "reset.scss";
тут еще можно добавить в название _ `_reset.scss`,`_normalize.scss` и тд

2021-12-31 12:21 UTC, jursylian commented on src/styles/blocks/calendar.scss
> +    cursor: pointer;
`cursor: pointer` лучше задать классу, а у состояния можно убрать.

2021-12-31 12:21 UTC, jursylian commented on src/styles/blocks/calendar.scss
> +  :first-child {
лучше использовать цикл или функцию для вычисления `margin` , если прописывать явно, то когда ты поменяешь ширину или длину, или какое-либо свойство - все поломается, поэтому лучше создать переменные на основе `size & gap` и с помощью них вычислить расстояние.

2021-12-31 12:21 UTC, jursylian commented on src/styles/blocks/calendar.scss
> +  width: 713px;
для  указания `width`  календаря лучше воспользоваться вычислениями на основе переменных ширина ячейки, расстояние между ними `gap`

2021-12-31 14:55 UTC, maksym-mishchanchuk commented
Дякую, за правки!)

2022-01-03 19:08 UTC, Anna-Tkachenko requested changes
Don't see demo link

2022-01-04 06:23 UTC, Anna-Tkachenko requested changes

2022-01-04 06:23 UTC, Anna-Tkachenko commented on src/index.html
> +      <section class="calendar">
Add start day and month length modifiers for calendar
![image](https://user-images.githubusercontent.com/30314756/148017895-7dec5bfb-a7cb-42a6-ad7c-40cb79a3b887.png)

2022-01-04 14:04 UTC, Anna-Tkachenko approved these changes

2022-01-04 14:04 UTC, Anna-Tkachenko commented on src/styles/blocks/calendar.scss
> +    transition: 0.5s;
Set property to transition

2022-01-04 14:04 UTC, Anna-Tkachenko commented on src/styles/blocks/calendar.scss
> +    transition: 0.5s;
Move it to general selector

2023-07-13 17:48 UTC, closed without merging