calendar
mate-academy/layout_calendar pull request #509
Opened 2022-01-20 18:31 UTC by mykolahuryn

2022-01-21 15:19 UTC, vkryvytskyy requested changes

2022-01-21 15:19 UTC, vkryvytskyy commented on README.md
> +- [DEMO LINK](https://mykolahuryn.github.io/layout_calendar/)
https://user-images.githubusercontent.com/38065883/150552047-a5bacd45-8108-436f-9f4c-a34317a5cfcb.mov

При изменении этих классов должен меняться и внешний вид календаря, первый день месяца должен перемещаться на новый день недели, и количество дней в месяце тоже должно меняться

2022-01-25 12:51 UTC, aliceblunt8 requested changes

2022-01-25 12:51 UTC, aliceblunt8 commented on src/styles/main.scss
> +  @for $index from 1 to 31 {
```suggestion
  @for $index from 1 through 31 {
```

![image](https://user-images.githubusercontent.com/57598825/150980159-3caacc97-af6a-4fe8-bc86-89624b51cdf9.png)

2022-01-26 14:56 UTC, aliceblunt8 approved these changes

2024-10-25 09:22 UTC, closed without merging