calendar
mate-academy/layout_calendar pull request #536
Opened 2022-01-27 06:31 UTC by AnnSerdechna

- [DEMO LINK](https://AnnSerdechna.github.io/layout_calendar/)
- [TEST REPORT LINK](https://AnnSerdechna.github.io/layout_calendar/report/html_report/)

2022-01-27 06:52 UTC, Ol-Lav requested changes
Календар просто супер! Але потрібно внести певні правки. В першу чергу додати   calendar-start-day та calendar__month-length, щоб можна було змінювати кількість днів та перший день місяця.

2022-01-27 06:52 UTC, Ol-Lav commented on src/index.html
> +    <div class="calendar">
має мати також  "calendar-start-day--sun calendar__month-length--29"

2022-01-27 06:52 UTC, Ol-Lav commented on src/styles/_variables.scss
> +$margin-left: $calendar-width - ($square-size + 5px);
це не буде працювати при зміні першого дня

2022-01-27 06:52 UTC, Ol-Lav commented on src/styles/blocks/calendar.scss
> +      }
зараз поки у тебе не можна змінити кількість днів

2022-01-27 11:43 UTC, Ol-Lav approved these changes
Супер! Чудова робота!

2022-01-27 15:08 UTC, Ihor-Karpyn requested changes

2022-01-27 15:08 UTC, Ihor-Karpyn commented on src/index.html
> +      <div class="calendar__day calendar__day--1"></div>
fix in all places

```suggestion
      <div class="calendar__day></div>
```

2022-01-27 15:08 UTC, Ihor-Karpyn commented on src/styles/blocks/calendar.scss
> +      }
```suggestion
      &:nth-child(#{$i})::before {
          content: "#{$i}";
      }
```

2022-01-28 10:08 UTC, Ihor-Karpyn approved these changes

2024-12-05 14:27 UTC, closed without merging