Calendar HW
mate-academy/layout_calendar pull request #538
Opened 2022-01-27 07:52 UTC by Ostafii4uk

- [DEMO LINK](https://Ostafii4uk.github.io/layout_calendar/)

2022-01-27 17:44 UTC, addKiwi approved these changes
Гарна робота, ти впорався!

2022-01-27 17:44 UTC, addKiwi commented on src/index.html
> +    >
Я закидував все в один рядок і тоді не викидувало помилку

2022-01-27 17:44 UTC, addKiwi commented on src/styles/blocks/calendar.scss
> +$padings-size: 20px;
Краще використовувати окремий файл так як уже створив папку utils

2022-01-27 17:44 UTC, addKiwi commented on src/styles/blocks/calendar.scss
> +  "set" 5,
fri, sat

2022-01-28 07:17 UTC, Ostafii4uk commented on src/styles/blocks/calendar.scss
> +  "set" 5,
Навіть не замітив)

2022-01-28 07:17 UTC, Ostafii4uk commented on src/styles/blocks/calendar.scss
> +$padings-size: 20px;
ок

2022-01-28 07:18 UTC, Ostafii4uk commented on src/index.html
> +    >
буду пробувати

2022-01-28 07:19 UTC, Ostafii4uk commented on src/index.html
> +    >
Теж спрацювало, дякую

2022-01-28 07:20 UTC, Ostafii4uk commented on src/styles/blocks/calendar.scss
> +$padings-size: 20px;
Добре

2022-01-28 10:07 UTC, Ihor-Karpyn requested changes

2022-01-28 10:07 UTC, Ihor-Karpyn commented on src/styles/blocks/calendar.scss
> +  margin: auto;
bem

2022-01-28 10:07 UTC, Ihor-Karpyn commented on src/styles/blocks/calendar.scss
> +
https://mateacademy.slack.com/archives/C02T596SHUZ/p1643298376583479

2022-01-31 19:50 UTC, solaryasha requested changes

2022-01-31 19:50 UTC, solaryasha commented on src/styles/blocks/calendar.scss
> +    transition: all 0.5s linear;
No no and no. Опиши для яких властивостей задаєш `transition`

2022-02-01 15:36 UTC, Ostafii4uk commented on src/styles/blocks/calendar.scss
> +    transition: all 0.5s linear;
Ok

2022-02-02 16:40 UTC, solaryasha approved these changes

2022-02-02 22:28 UTC, closed without merging