added calendar
mate-academy/layout_calendar pull request #716
Opened 2022-05-11 11:32 UTC by vsupruniuk

- [DEMO LINK](https://vsupruniuk.github.io/layout_calendar/)
- [TEST REPORT LINK](https://vsupruniuk.github.io/layout_calendar/report/html_report/)

2022-05-14 16:15 UTC, Samaev requested changes
Работа отменная, кратко и можно брать за образец, но есть один момент, проверь пожалуйста по чеклисту п. 9

2022-05-14 16:15 UTC, Samaev commented on src/styles/variables.scss
> +$calendar-pading: 10px;
в чеклисте есть условие чтобы календарь оставался рабочим 31 день и начинался с понедельника, если количество дней в месяце будет невалижным, например 27, а у тебя я так понимаю построится на 27 дней

2022-05-16 11:35 UTC, Samaev approved these changes
Good job!

2022-05-17 09:18 UTC, Olexandr6 approved these changes
Almost done👍

2022-05-17 09:18 UTC, Olexandr6 commented on src/styles/main.scss
> +.calendar {
[Checklist](https://github.com/mate-academy/layout_calendar/blob/master/checklist.md) 3rd point

2022-05-17 09:18 UTC, Olexandr6 commented on src/styles/reset.scss
> +}
This is not resetting. Create a normalize file for this purpose

2022-05-17 09:18 UTC, Olexandr6 commented on src/styles/main.scss
> +      cursor: pointer;
the cursor must be always when user hovers day block, so move it to the main selector

2024-01-13 13:41 UTC, closed without merging