Add calendar
mate-academy/layout_calendar pull request #721
Opened 2022-05-14 18:22 UTC by ik-web

- [DEMO LINK](https://ik-web.github.io/layout_calendar/)

2022-05-16 09:02 UTC, AKomashchuk requested changes

2022-05-16 09:02 UTC, AKomashchuk commented on src/styles/blocks/page.scss
> +  }
Flex-dicection лишній

2022-05-16 09:02 UTC, AKomashchuk commented on src/styles/blocks/month.scss
> +}
.month__day => &__day  так як фунція знаходиться всередині .month

2022-05-16 09:02 UTC, AKomashchuk commented on src/styles/blocks/month.scss
> +    }
Чи варто дублювати transform для : :before?

2022-05-16 09:02 UTC, AKomashchuk commented on src/styles/_mixins.scss
> +}
transition-property

2022-05-16 11:23 UTC, AKomashchuk approved these changes

2022-05-16 11:23 UTC, AKomashchuk commented
👍)

2022-05-16 11:23 UTC, ik-web commented on src/styles/blocks/page.scss
> +  }
Fixed

2022-05-16 11:24 UTC, ik-web commented on src/styles/blocks/month.scss
> +}
Fixed

2022-05-16 11:24 UTC, ik-web commented on src/styles/blocks/month.scss
> +    }
Варто. Інакше картинка не буде підійматися.

2022-05-16 11:24 UTC, ik-web commented on src/styles/_mixins.scss
> +}
Fixed

2022-05-17 13:51 UTC, mkyloa approved these changes
трохи з анімаціями перемудрив)

2022-09-14 14:01 UTC, closed without merging