Made calendar
mate-academy/layout_calendar pull request #727
Opened 2022-05-15 19:39 UTC by mira1zu

- [DEMO LINK](https://mira1zu.github.io/layout_calendar/)

2022-05-16 06:42 UTC, k0nstrukt-or requested changes
:fire: . Супер , один штришок і готово!

2022-05-16 06:42 UTC, k0nstrukt-or commented on src/styles/blocks/calendar.scss
> +
ти ж маєш змінну з таким значенням.

2022-05-16 06:48 UTC, mira1zu commented on src/styles/blocks/calendar.scss
> +
Упс)

2022-05-16 06:55 UTC, k0nstrukt-or approved these changes

2022-05-17 08:54 UTC, Olexandr6 approved these changes
Good job👍

2022-05-17 08:54 UTC, Olexandr6 commented on src/styles/blocks/calendar.scss
> +    transition: background, transform 0.5s ease;
```suggestion
    transition: background 0.5s, transform 0.5s ease;
```

2022-05-17 08:54 UTC, Olexandr6 commented on src/styles/blocks/calendar.scss
> +    &:hover {
```suggestion
    cursor: pointer;
    
    &:hover {
```

2022-12-08 22:08 UTC, closed without merging