CALENDAR
mate-academy/layout_calendar pull request #777
Opened 2022-05-21 13:34 UTC by leonid-levtseniuk

2022-05-23 21:05 UTC, marina-tilniak requested changes
- додай плавність для анімаціїї
- календар має бути в центрі сторінки(дивись завдання)

2022-05-23 21:05 UTC, marina-tilniak commented on src/index.html
> +    <main class="calendar">
додай модифікатори для того, щоб можна було змінювати день тижня та кількість днів у місяці

2022-05-25 08:40 UTC, leonid-levtseniuk commented
не дуже розумію як його правильно робити конкретно в цьому завданні, якщо чесно, але надіюсь щось таке має бути

2022-05-25 20:49 UTC, marina-tilniak requested changes

2022-05-25 20:49 UTC, marina-tilniak commented on src/styles/main.scss
> +  }
в залежності від того скільки днів ми хочемо показувати деякі клітинки потрібно не показувати 
content тут не потрібно задавати

2022-05-25 20:49 UTC, marina-tilniak commented on src/styles/main.scss
> +  }
в залежності від того який день обраний як перший потрібну змінювати margin-left для першої клітинки
content тут не потрібно задавати

2022-05-25 20:49 UTC, marina-tilniak commented on src/index.html
> +      class="calendar calendar--start-day calendar--month-length">
```suggestion
      class="calendar calendar--start-day--mon calendar--month-length--30">
```

2022-05-26 15:42 UTC, marina-tilniak requested changes

2022-05-26 15:42 UTC, marina-tilniak commented on src/styles/main.scss
> +$month-length: 28;
тут має бути 31

2022-05-26 15:42 UTC, marina-tilniak commented on src/styles/main.scss
> +  }
```suggestion
  @for $number from $least-month-length through $month-length {
    &__month-length--#{$month-length} :nth-last-child(-n + #{31 - $number}) {
      display: none;
    }
  }
```

2022-05-26 15:42 UTC, marina-tilniak commented on src/styles/main.scss
> +
```suggestion
$days:
    'mon' 0,
    'tue' 1,
    'wed' 2,
    'thu' 3,
    'fri' 4,
    'sat' 5,
    'sun' 6;

```

2022-05-26 15:42 UTC, marina-tilniak commented on src/styles/main.scss
> +  }
```suggestion
  @each $day, $number in $days {
    &__start-day--#{$day} :first-child {
      margin-left: $first-cell-margin-left + $cell-size * $number;
    }
  }
```

2022-05-26 15:42 UTC, marina-tilniak commented on src/styles/main.scss
> +  }
так мало би працювати, лише перевір $first-cell-margin-left, там має бути ширина клітинки і gap

2022-05-26 16:45 UTC, leonid-levtseniuk commented on src/styles/main.scss
> +  }
єдине, що там клітинки не зсуваються якщо кількість днів змінюється, там все прописано для цього, чому воно не працює - не розумію

2022-05-26 16:46 UTC, leonid-levtseniuk commented
єдине, що там клітинки не зсуваються якщо кількість днів змінюється, там все прописано для цього, чому воно не працює - не розумію

2022-05-26 18:00 UTC, marina-tilniak commented on src/styles/main.scss
> +    &__month-length--#{$month-length} :nth-last-child(-n + #{31 - $number}) {
```suggestion
    &__month-length--#{$number} :nth-last-child(-n + #{31 - $number}) {
```

2022-05-26 18:00 UTC, marina-tilniak commented on src/styles/main.scss
> +$least-month-length: 29;
```suggestion
$least-month-length: 28;
```

2022-05-26 18:00 UTC, marina-tilniak commented on src/styles/main.scss
> +  }
виправ це

2022-05-26 18:10 UTC, leonid-levtseniuk commented on src/styles/main.scss
> +  }
Якщо в 73 рядочку змінюю $month-length на $number, то знову повторюється та історія, коли не зникали останні клітинки

2022-05-26 18:16 UTC, leonid-levtseniuk commented
Якщо виправляю $first-cell-margin-left щоб там були лише $cell-size I $gap, то виходить отаке:

<img width="1680" alt="Знімок екрана 2022-05-26 о 21 16 10" src="https://user-images.githubusercontent.com/104631433/170550637-bd572617-3430-4f64-bd5c-bd177e350f2e.
<img width="1680" alt="Знімок екрана 2022-05-26 о 21 16 24" src="https://user-images.githubusercontent.com/104631433/170550691-eac26f1c-8d69-435b-9cc3-f8974ad82765.png">
png">

@marina-tilniak

2022-05-27 15:57 UTC, marina-tilniak requested changes

2022-05-27 15:57 UTC, marina-tilniak commented on src/styles/main.scss
> +  (#{$cell-size} + #{$gap}) * 6);
```suggestion
$cell-margin-left: calc(#{$cell-size} + #{$gap});
```

2022-05-27 15:57 UTC, marina-tilniak commented on src/styles/main.scss
> +  max-height: $main-height;
delete it

2022-05-27 15:57 UTC, marina-tilniak commented on src/styles/main.scss
> +    }
```suggestion
      margin-left: calc(#{$cell-margin-left} * #{$number});
    }
```

2022-05-27 15:57 UTC, marina-tilniak commented on src/styles/main.scss
> +    }
delete it

2022-05-27 15:57 UTC, marina-tilniak commented on src/styles/main.scss
> +  (#{$cell-size} + #{$gap}) * 6);
ти зсуваєгш клітинку на її ширину і gap, а множиш в залежності від модифікатора в циклі

2022-05-27 16:10 UTC, leonid-levtseniuk commented on src/styles/main.scss
> +  max-height: $main-height;
якщо я це все видаляю, то воно розлізається по всьому екрану

2022-05-27 16:13 UTC, leonid-levtseniuk commented on src/styles/main.scss
> +  max-height: $main-height;
<img width="1680" alt="Знімок екрана 2022-05-27 о 19 12 36" src="https://user-images.githubusercontent.com/104631433/170738004-68d41093-d284-41b1-88ce-cb0f15cf0b64.png">

2022-05-27 16:15 UTC, leonid-levtseniuk commented on src/styles/main.scss
> +    }
ну я виправив все, і в результаті нічого, якщо не видаляти 35-37 рядок, де вказані max-width, gap, padding, то виходить отаке:

<img width="1680" alt="Знімок екрана 2022-05-27 о 19 15 15" src="https://user-images.githubusercontent.com/104631433/170738391-ff749a94-2d87-4ebf-955c-e9591c1bd837.png">

2022-05-27 16:52 UTC, marina-tilniak commented on src/styles/main.scss
> +  max-height: $main-height;
max-height: $main-height лише видали, я випалково видіолила більше) не розумію для чого цей стиль

2022-05-27 16:54 UTC, marina-tilniak commented on src/styles/main.scss
> +    }
ну так все добре, ти пробував міняти модифікатор на wed наприклад?

2022-05-27 17:54 UTC, leonid-levtseniuk commented on src/styles/main.scss
> +    }
о небо! і справді все ок, я просто не дуже розумів, як воно повинно виглядати в кінцевому результаті

все, пушу

2022-05-27 18:09 UTC, marina-tilniak approved these changes

2022-05-27 18:10 UTC, closed without merging