Develop
mate-academy/layout_calendar pull request #841
Opened 2022-06-13 21:54 UTC by NazikVr

- [DEMO LINK](https://nazikvr.github.io/layout_calendar/)
- [TEST REPORT LINK](https://nazikvr.github.io/layout_calendar/report/html_report/)

2022-06-16 10:03 UTC, Bohdan-Maksymiuk requested changes

2022-06-16 10:03 UTC, Bohdan-Maksymiuk commented on src/index.html
> +        <div class="month__day month__day--first--tue"></div>
it should be class for calendar container 
`month__day--first--tue`

2022-06-16 10:03 UTC, Bohdan-Maksymiuk commented on src/index.html
> +      <div class="month__flex month__flex--length--28">
you don't need class for main - make your div as this BEM block

2022-08-28 00:47 UTC, NazikVr commented on src/index.html
> +        <div class="month__day month__day--first--tue"></div>
when i add this class for calendar container 'month__flex--first--fri', this solushion don't working

2022-08-30 13:25 UTC, valerii-derkach requested changes

2022-08-30 13:25 UTC, valerii-derkach commented on src/index.html
> +          <div class="month__day"></div>
```suggestion
        <div class="month__flex month__flex--length--28  month__flex--first--fri">
          <div class="month__day"></div>
          <div class="month__day"></div>
```

2022-08-30 13:25 UTC, valerii-derkach commented on src/styles/main.scss
> +    }
```suggestion
    @each $name, $number in $numbers {
      &--first--#{$name} {
        .month__day:first-child {
          margin-left: #{$number};
        }
      }
    }
```

2022-08-30 13:25 UTC, valerii-derkach commented on src/styles/main.scss
> +    "sun" 606px;
```suggestion
    "tue" 1,
    "wed" 2,
    "thu" 3,
    "fri" 4,
    "sat" 5,
    "sun" 6;
```

2022-08-30 13:25 UTC, valerii-derkach commented on src/styles/main.scss
> +    }
margin-left: $ number * ($ `ширина блока` + $ `відстань між блоками`);

2022-09-02 10:34 UTC, valerii-derkach approved these changes

2025-10-08 16:34 UTC, closed without merging