calendar was created
mate-academy/layout_calendar pull request #846
Opened 2022-06-14 12:36 UTC by blcts

- [DEMO LINK](https://blcts.github.io/layout_calendar/)
- [TEST REPORT LINK](https://blcts.github.io/layout_calendar/report/html_report/)

2022-06-14 18:47 UTC, chernobrovin requested changes
![image](https://user-images.githubusercontent.com/99829944/173665549-88995f6b-58de-47a8-aa9f-fb8e16751bdd.png)

пункт 10 чек ліста [FUNCTIONALITY] - Your project should work correctly (have 31 days and start on Monday) with invalid modifier values, like start-day--ghy or days--27.

а в тебе при зміні данних все ламається...

2022-06-14 18:47 UTC, chernobrovin commented on src/styles/reset.scss
> +}
то ти так вже по-дорослому reset так reset :smile:

2022-06-14 18:47 UTC, chernobrovin commented on src/styles/_variables.scss
> +$paddings: 10px;
Пункт 11 чек ліста [STYLES] - Don't be greedy, add some top paddings, so the top row don't go over top of the page on hover.

В тебе "одиничка" наполовину уходить за межі екрану при наведенні

2022-06-14 18:47 UTC, chernobrovin commented on src/styles/calendar.scss
> +    transition: background-color 0.5s, transform 0.5s;
пункт 12 чек ліста [CODE STYLE] - Remember about styles properties order - ([css order](https://codeguide.academy/html-css.html#css-order))

в тебе все в купі)

2022-06-14 18:47 UTC, chernobrovin commented on src/styles/_variables.scss
> +$marginLeft: $size + $gap * 3;
а навіщо тобі тут потрійний відступ?

2022-06-14 19:14 UTC, blcts commented on src/styles/_variables.scss
> +$marginLeft: $size + $gap * 3;
переменную так рассчитываю )

2022-06-14 19:22 UTC, chernobrovin commented on src/styles/_variables.scss
> +$marginLeft: $size + $gap * 3;
`$marginLeft: $size + $gap ` ну так - ок, а зачем *3?))

2022-06-14 20:44 UTC, chernobrovin approved these changes
the best! :green_heart:

2022-06-15 07:38 UTC, ivan-kadykalo requested changes
Almost done, fix that extra space at the right
![image](https://user-images.githubusercontent.com/57747481/173770395-7571a1f6-9323-483c-b215-0a33ebb88305.png)

2022-06-15 15:03 UTC, ivan-kadykalo approved these changes
Fix that margin on right side
![image](https://user-images.githubusercontent.com/57747481/173860725-ab65ede9-2092-4b0f-b041-c67430d9b03e.png)

2023-04-19 13:51 UTC, closed without merging