task was completed
mate-academy/layout_calendar pull request #878
Opened 2022-06-16 21:17 UTC by Glebatikot

- [DEMO LINK](https://Glebatikot.github.io/layout_calendar/)
- [TEST REPORT LINK](https://Glebatikot.github.io/layout_calendar/report/html_report/)

2022-06-17 07:29 UTC, ivan-kadykalo requested changes
Student review first ⚠️

2022-06-17 16:13 UTC, ivan-kadykalo requested changes

2022-06-17 16:13 UTC, ivan-kadykalo commented on src/index.html
> +    <div class="calendar calendar--start--day--sun calendar--month-lenght--30">
```suggestion
    <div class="calendar calendar--start--day--sun calendar--month-length--30">
```

2022-06-17 16:29 UTC, Glebatikot commented on src/index.html
> +    <div class="calendar calendar--start--day--sun calendar--month-lenght--30">
hahahha))

2022-06-20 05:40 UTC, VETALEK reviewed
You still need a student review 😉

2022-06-20 08:16 UTC, Yura-Lysenko commented
looks good!!)

2022-06-20 08:18 UTC, Yura-Lysenko approved these changes

2022-06-20 08:42 UTC, VETALEK requested changes
mind placing your calendar in the center 😉
and you need some space from the top

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/55802630/174561821-401602cc-4a32-4558-bb06-704f5244ed13.png">

2022-06-20 08:42 UTC, VETALEK commented on src/styles/normilize.scss
> +  margin: 0;
are you sure you need to reset all the margins?

2022-06-20 08:42 UTC, VETALEK commented on src/styles/normilize.scss
> +  margin: 0;
you use only `<div>`s, they don't even have default `margin` 😭

2022-06-20 09:07 UTC, VETALEK approved these changes
GJ 🔥

2022-06-30 07:18 UTC, closed without merging