Initial
mate-academy/layout_calendar pull request #904
Opened 2022-07-02 21:35 UTC by MihailKostov

https://MihailKostov.github.io/layout_calendar/

I didn't understand what do you mean here:
  -Implement `start-day` modifier for the `calendar` with `mon`, `tue`, `wed`, `thu`, `fri`, `sat` and `sun` values
    - The month should start at the correct column (Monday is the 1st, Friday is the 5th)

2022-07-05 15:12 UTC, ArturErmolenko requested changes
Также должен быть модификатор количества дней в месяца ,то 28 до 31

2022-07-05 15:12 UTC, ArturErmolenko commented on src/index.html
> +      <div class="calendar">
```suggestion
      <div class="calendar calendar__start-day--mon">
```
У календаря должен быть модификатор который по сути считает отступ влево, чтобы если ты изменил модификатор на wed то календарь начинался с 3 столбика как в настоящем календаре со среды

2022-07-05 15:12 UTC, ArturErmolenko commented on src/index.html
> +        <div class="calendar__start-day"></div>
```suggestion
        <div class="calendar__day"></div>
```

2022-07-08 21:03 UTC, marina-tilniak requested changes
checklist point 9

2022-07-12 14:31 UTC, alexandra-protyanova approved these changes
Well done!

2022-07-12 14:31 UTC, alexandra-protyanova commented on src/styles/blocks/calendar.scss
> +$cell-size: 100px;
it is better to remove to different file

2022-07-12 14:31 UTC, alexandra-protyanova commented on src/styles/blocks/calendar.scss
> +    box-sizing: border-box;
move to `*`

2026-03-23 18:20 UTC, closed without merging