done
mate-academy/layout_calendar pull request #944
Opened 2022-07-18 16:34 UTC by savchuksavchuk

[DEMO LINK](https://savchuksavchuk.github.io/layout_calendar/)
[TEST REPORT LINK](https://savchuksavchuk.github.io/layout_calendar/report/html_report/)

2022-07-19 20:37 UTC, marina-tilniak requested changes
Потрібно додати файли зі стилями на GitHub

2022-07-19 20:37 UTC, marina-tilniak commented on src/index.html
> +        <div class="calendar__day calendar__day--number_31"></div>
видали зайві класи, для кожного div  має бути лише клас calendar__day
Використовуй nth-child

2022-09-17 07:30 UTC, SanyaBratashchuk requested changes

2022-09-17 07:30 UTC, SanyaBratashchuk commented on src/index.html
> +        <div class="calendar__day calendar__day--number_31"></div>
Didn't fix

2024-12-28 11:06 UTC, closed without merging