solution
mate-academy/layout_calendar pull request #95
Opened 2021-05-31 17:10 UTC by Fiannn

- [DEMO LINK](https://Fiannn.github.io/layout_calendar/)
- [TEST REPORT LINK](https://Fiannn.github.io/layout_calendar/report/html_report/)

2021-06-01 10:13 UTC, vkryvytskyy requested changes
![image](https://user-images.githubusercontent.com/38065883/120306970-1f149100-c2db-11eb-8315-452e3aa2c4be.png)

https://user-images.githubusercontent.com/38065883/120306975-2176eb00-c2db-11eb-83a8-e5e1fcc175b3.mov

Please check that you set correct branch in repo settings

2021-06-01 10:20 UTC, Fiannn commented
![image](https://user-images.githubusercontent.com/83066417/120307739-0193f700-c2dc-11eb-90e5-2b4358d074b2.png)
i didnt change anything...

2021-06-01 10:24 UTC, Fiannn commented
![Анимация](https://user-images.githubusercontent.com/83066417/120308364-b3cbbe80-c2dc-11eb-9e1b-4b238af2513a.gif)

2021-06-01 10:26 UTC, Fiannn commented
added proof in gif format

2021-06-03 09:26 UTC, vkryvytskyy requested changes

2021-06-03 09:26 UTC, vkryvytskyy commented on src/styles/calendar.scss
> +  $day-week:
![image](https://user-images.githubusercontent.com/38065883/120621793-e30e3700-c466-11eb-9810-28c915ad8c6a.png)
I can't see this modifier

2021-06-03 09:56 UTC, vkryvytskyy approved these changes
Add class to the calendar and set it to 29 days, to show it works

2024-05-24 16:57 UTC, closed without merging